"use client";
import {useState} from "react";
import {useSearchParams} from "next/navigation";
import {api} from "../../lib/api";

const steps=["new","confirmed","processing","shipped","delivered"];
export default function TrackOrder(){const searchParams=useSearchParams();const store=searchParams.get("store")||"";const[order,setOrder]=useState<any>(null),[form,setForm]=useState({order:"",phone:""}),[loading,setLoading]=useState(false),[error,setError]=useState("");
async function track(e:React.FormEvent){e.preventDefault();if(!store){setError("Store is required. Open tracking from your store.");return;}setLoading(true);setError("");try{const d=await api("/api/public/stores/"+encodeURIComponent(store)+"/orders/track?order="+encodeURIComponent(form.order)+"&phone="+encodeURIComponent(form.phone));setOrder(d)}catch(e:any){setError(e.message||"Order not found")}finally{setLoading(false)}}
const current=order?steps.indexOf(order.status):0;
return <main style={{minHeight:"100vh",background:"#f7f4ee",padding:"48px 20px",fontFamily:"Arial,sans-serif"}}><div style={{maxWidth:680,margin:"auto"}}><a href="/" style={{fontWeight:900,color:"#111",textDecoration:"none"}}>HEPRA</a><h1 style={{fontSize:42,margin:"50px 0 10px"}}>Track your order</h1><p>Enter your order number and phone number to see the latest status.</p><form onSubmit={track} style={{background:"#fff",padding:24,border:"1px solid #ddd",marginTop:24,display:"grid",gap:12}}><input required placeholder="Order number e.g. HP-12345678" value={form.order} onChange={e=>setForm({...form,order:e.target.value})}/><input required placeholder="Phone number" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><button disabled={loading} style={{padding:14,background:"#111",color:"#fff",border:0}}>{loading?"Checking…":"Track order"}</button></form>{error&&<p style={{color:"#b42318"}}>{error}</p>}{order&&<section style={{background:"#fff",padding:24,marginTop:20,border:"1px solid #ddd"}}><div style={{display:"flex",justifyContent:"space-between"}}><b>{order.orderNumber}</b><strong>₹{Number(order.total).toLocaleString("en-IN")}</strong></div><p>Payment: {order.paymentStatus}</p><div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:8,marginTop:30}}>{steps.map((s,i)=><div key={s} style={{textAlign:"center",fontSize:12}}><div style={{height:10,borderRadius:10,background:i<=current?"#111":"#ddd"}}/><span>{s}</span></div>)}</div></section>}</div></main>}