"use client";

import {useEffect,useMemo,useState} from "react";
import {useParams,useSearchParams} from "next/navigation";\nimport Script from "next/script";

type Product={id?:string;_id?:string;name:string;price:number;stock?:number;image?:string;status?:string};
declare global { interface Window { Cashfree?: any } }\ntype Store={id:string;name:string;slug:string;category?:string;theme?:string;published?:boolean};

const API="/api/public/stores";

export default function Storefront(){
 const params=useParams<{slug:string}>();const searchParams=useSearchParams();
 const [store,setStore]=useState<Store|null>(null),[products,setProducts]=useState<Product[]>([]),[cart,setCart]=useState<Product[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[checkout,setCheckout]=useState(false),[customer,setCustomer]=useState({name:"",phone:"",email:"",address:""}),[order,setOrder]=useState<any>(null),[ordering,setOrdering]=useState(false);
 useEffect(()=>{(async()=>{try{const r=await fetch(`${API}/${encodeURIComponent(params.slug)}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.message||"Store not found");setStore(d.store||d);setProducts(Array.isArray(d.products)?d.products:[])}catch(e:any){setError(e.message||"Unable to load store")}finally{setLoading(false)}})()},[params.slug]);
 const total=useMemo(()=>cart.reduce((s,p)=>s+Number(p.price||0),0),[cart]);
 function add(p:Product){setCart(x=>[...x,p])}\n async function payOnline(e:React.FormEvent){e.preventDefault();if(!cart.length)return;setOrdering(true);setError("");try{const counts=new Map<string,number>();cart.forEach(p=>counts.set(String(p.id||p._id),(counts.get(String(p.id||p._id))||0)+1));const r=await fetch(`${API}/${encodeURIComponent(params.slug)}/payment`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer,items:[...counts].map(([productId,quantity])=>({productId,quantity}))})});const d=await r.json();if(!r.ok)throw new Error(d.message||"Unable to start payment");if(!window.Cashfree)throw new Error("Cashfree checkout is loading. Please try again.");const cashfree=window.Cashfree({mode:process.env.NEXT_PUBLIC_CASHFREE_MODE==="production"?"production":"sandbox"});await cashfree.checkout({paymentSessionId:d.paymentSessionId,redirectTarget:"_self"});}catch(e:any){setError(e.message||"Unable to start payment")}finally{setOrdering(false)}}\n async function placeOrder(e:React.FormEvent){e.preventDefault();if(!cart.length)return;setOrdering(true);setError("");try{const counts=new Map<string,number>();cart.forEach(p=>counts.set(String(p.id||p._id), (counts.get(String(p.id||p._id))||0)+1));const r=await fetch(`${API}/${encodeURIComponent(params.slug)}/orders`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer,items:[...counts].map(([productId,quantity])=>({productId,quantity}))})});const d=await r.json();if(!r.ok)throw new Error(d.message||"Unable to place order");setOrder(d);setCart([]);setCheckout(false)}catch(e:any){setError(e.message||"Unable to place order")}finally{setOrdering(false)}}
 if(loading)return <><Script src="https://sdk.cashfree.com/js/v3/cashfree.js" strategy="afterInteractive" /><main className="public-store"><div className="store-loading">Loading store…</div></main>;
 if(error||!store)return <main className="public-store"><div className="store-error"><h1>Store unavailable</h1><p>{error||"This store could not be found."}</p></div></main>;
 return <main className="public-store">
  <header className="store-header"><a href="/" className="store-brand">HEPRA</a><div><b>{store.name}</b><span>{store.category||"Online Store"}</span></div><button className="cart-button" onClick={()=>document.getElementById("cart")?.scrollIntoView({behavior:"smooth"})}>Cart ({cart.length})</button></header>
  <section className="store-hero"><span>ONLINE STORE</span><h1>{store.name}</h1><p>Shop directly from our store. Simple, fast and mobile-friendly.</p></section>
  <section className="store-products"><div className="store-section-head"><div><small>CATALOG</small><h2>Featured products</h2></div><span>{products.length} products</span></div>
   {products.length===0?<div className="store-empty">No products available yet.</div>:<div className="store-grid">{products.map(p=><article className="store-card" key={p.id||p._id}><div className="store-image">{p.image?<img src={p.image} alt={p.name}/>:<span>HEPRA</span>}</div><div className="store-card-body"><h3>{p.name}</h3><strong>₹{Number(p.price||0).toLocaleString("en-IN")}</strong><button disabled={p.stock===0} onClick={()=>add(p)}>{p.stock===0?"Out of stock":"Add to cart"}</button></div></article>)}</div>}
  </section>
  <section id="cart" className="store-cart"><div><small>YOUR CART</small><h2>Cart</h2></div>{cart.length===0?<p>Your cart is empty.</p>:<><div className="cart-items">{cart.map((p,i)=><div key={i}><span>{p.name}</span><b>₹{Number(p.price||0).toLocaleString("en-IN")}</b></div>)}</div><div className="cart-total"><span>Total</span><strong>₹{total.toLocaleString("en-IN")}</strong></div><button className="checkout-button" onClick={()=>setCheckout(true)}>Continue to checkout</button>{checkout&&<form className="checkout-form" onSubmit={placeOrder}><h3>Customer details</h3><input required placeholder="Full name" value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/><input required placeholder="Phone number" value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/><input type="email" placeholder="Email (optional)" value={customer.email} onChange={e=>setCustomer({...customer,email:e.target.value})}/><textarea placeholder="Delivery address" value={customer.address} onChange={e=>setCustomer({...customer,address:e.target.value})}/><div><b>Payment method</b><div className="payment-choice"><button type="button" onClick={()=>setError("")}>COD</button><button type="button" onClick={(e)=>payOnline(e as any)}>UPI / Card</button></div><button className="checkout-button" disabled={ordering}>{ordering?"Processing…":"Place COD order"}</button></div></form>}{order&&<div className="order-success"><h3>Order placed 🎉</h3><p>Order <b>{order.orderNumber}</b> confirmed.</p><strong>₹{Number(order.total).toLocaleString("en-IN")}</strong></div>}</>}</section>
  <footer className="store-footer">Powered by <b>HEPRA</b></footer>
 </main>
}